services:
  db:
    image: mysql:8.0
    container_name: mysql_usercrud
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - usercrud-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - ./backend:/var/www/html:rw
    networks:
      - usercrud-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        API_URL: "http://backend:80/api"
    container_name: frontend_static
    ports:
      - "3000:80"
    networks:
      - usercrud-net

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium_chrome
    ports:
      - "4444:4444"
    shm_size: 2g
    depends_on:
      - frontend
    networks:
      - usercrud-net

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "${JENKINS_PORT}:8080"
      - "5000:5000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    container_name: ci_jenkins
    networks:
      - usercrud-net

  tests:
    build: ./Pruebas
    container_name: selenium_tests
    depends_on:
      - frontend
      - backend
      - db
    networks:
      - usercrud-net

volumes:
  db_data:
  jenkins_home:

networks:
  usercrud-net:
    driver: bridge
